### ISSUE TITLE
Github Actions not created

### ISSUE THREAD

**Issue by MrJohnson-SixNinesIT** [lpm0073/cookiecutter-openedx-devops#16]
**Describe the bug**
At what point are the Github actions created? I've added the credentials to the Actions Secrets, and ran the terragrunt commands, but I am unable to see Github Actions being created. Is there something I am missing?

**Workflow**

1. Install CookieCutter.
2. Run CookieCutter Command to checkout repo.
3. Push code to private repo.
4. Add credentials and personal access token to Github Action Secrets
5. Run terragrunt commands.
6. Actions still not populated. 

**Expected behavior**
Github actions to be created to actually deploy OpenEdx to the created AWS infrastructure. 

Thank you for your time and work on this.

**Comment by lpm0073** [comment]
Hi @MrJohnson-SixNinesIT, the Github Actions are called from the workflows in the cookiecutter, but they are only instantiated (aka "created") at run-time from within Github's worker nodes. Here's a link to t
he general documentation to which i referred when I created the Open edX Github Actions library: [understanding-github-actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions). 

You'll find the console for the Gtihub Actions workflow inside the repository that you a.) created with Cookiecutter and b.) pushed to Github. See the screen for an example based on a Cookiecutter-generated repo for a platform named Stepwise Math: https://github.com/StepwiseMath/openedx_devops

<img width="1188" alt="Screen Shot 2022-08-26 at 21 19 42" src="https://user-images.githubusercontent.com/1178819/187010494-8c8190e9-ff66-487c-b420-884fd21e2167.png">

The source for the workflow highlighted in the screen shot above is located here: [https://github.com/StepwiseMath/openedx_devops/blob/main/.github/workflows/deploy-stepwise-prod.yml](https://github.com/StepwiseMath/openedx_devops/blob/main/.github/workflows/deploy-stepwise-prod.yml)

In the source code you'll find calls to the Github Actions. In the screen shot that follows you'll see calls to two different Github Actions, one provided by AWS (aws-actions) and another provided by Open edX Github Actions:

<img width="499" alt="Screen Shot 2022-08-26 at 21 21 09" src="https://user-images.githubusercontent.com/1178819/187010595-e43d3837-c759-4acf-991d-e7539e987849.png">

The source code for each, respectively is located at:
 - https://github.com/aws-actions/configure-aws-credentials
 - https://github.com/openedx-actions/tutor-k8s-init

hope that helps.
