### ISSUE TITLE
MongoDB required but missing

### ISSUE THREAD

**Issue by MrJohnson-SixNinesIT** [lpm0073/cookiecutter-openedx-devops#17]
**Describe the bug**
During the Deploy Github action there is a step that looks for a MongoDB as part of the created infrastructure. The Readme in the main branch also shows an example of building the MongoDB infrastructure and mentions it throughout. 

I've looked through the main branch and see no terraform code that will actually produce any MongoDB environment, and thus, the Deployment action fails. 

**Expected behavior**
The expected behavior is that the MongoDB infrastructure exists in code and is created, but neither appear to be true.

**Additional context**
I noticed there is a MongoDB branch that is ahead of master that has Mongo db modules and environment folder structure. What would be the best course of action to finish standing up my environment? Bring over those MongoDB files from the MongoDB branch (in the stacks and environments folders), running the Terragrunt commands against them, then running the Github Actions again?

Any insight you could provide on this would be greatly appreciated.

**Comment by lpm0073** [comment]
This afternoon I merged the mongodb branch into main and then tested the updated codebase on a couple of sites: mooc.moocweb.com, and web.stepwisemath.ai. Both of these are pre-production sites that are great for testing. everything appears to work fine. 

You'll find a new Cookiecutter parameter, stack_add_remote_mongodb, that defaults to 'N'. "No" means that you do not want to add a remote Mongo server to your stack. While the new remote MongoDB server option appears to work fine, it objectively adds complexity to the build, and so I'd avoid this option for now if your goal is to get something up and running as quickly as possible.

**Now then**, regarding your comment, that the main branch contained a github action that looked for a MongoDB (sic server). This is not the case. Best guess is that you somehow ended up running the Cookiecutter from the mongodb branch, and out of sequence. Or perhaps more accurately: this was the only way that i could re-produce your observed behavior. For the avoidance of any doubt, you're welcome to review the commit history of the deployment workflow, which has not changed much in the last 2 months: [.github/workflows/deploy-{namespace}.yml](https://github.com/lpm0073/cookiecutter-openedx-devops/commits/main/%7B%7Bcookiecutter.github_repo_name%7D%7D/.github/workflows/deploy-%7B%7Bcookiecutter.environment_name%7D%7D.yml)

**Comment by MrJohnson-SixNinesIT** [comment]
We've gone through our notes and what we have done, and we are fairly certain that we didn't use the mongo branch, and indeed, there is no MongoDB folders or files in our git repo. During the deployment build, we see this: 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/105312312/187452151-47138930-2fda-48db-a86f-5dc59626ffb8.png">

And here is the error we get from the logs:

```
File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/openedx/edx-platform/common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py", line 26, in forwards_func
    for course_index in split_modulestore.db_connection.find_matching_course_indexes(force_mongo=True):
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 499, in _check_session_support
    self._select_servers_loop(
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: client is configured to connect to a replica set named '' but this node belongs to a set named 'None', Timeout: 30s, Topology Description: <TopologyDescription id: 630cef05ebbf63ea4e936254, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=ConfigurationError("client is configured to connect to a replica set named '' but this node belongs to a set named 'None'")>]>
```

Thanks for the quick responses. At this point, we may just run a terragrunt run-all destroy and have to start from scratch, as we just want to get something up and running as soon as possible.

So just to be sure everything is done right, we intend to do the following (assuming Environment_Name == Dev):

1. Run the CookieCutter command with our parameters (we shouldn't have to worry about MongoDB because it should now take a parameter who's default value is "No"
2. Navigate to the openedx_develops folder.
3. Push the code to our repo.
4. Add our credentials to the actins' secrets
5. Navigate to /terraform/environments/Dev/vpc
6. terragrunt apply
7. Navigate to /terraform/environments/Dev/kubernetes
8. Run into build error
9. run terragrunt apply again
10. terragrunt apply
11. Navigate to /teerraform/environments/Dev
12. terragrunt run-all apply

And just from those steps, we should be have all of our infrastructure created. 
Then, in our Actions (thanks for your response on our previous question about this)  we run the workflows in the following order:

1. Build Optional Containers
2. Build openedx container
3. Deploy {environment name}

Does this look accurate to you? Once again, thanks.
